### ISSUE TITLE
Mouse control VIs are not available on the Mac

### ISSUE THREAD

**Issue by mbollini** [matrixx567/LabView_QuickDrop_AlignElements#1]
Mouse control VIs are not available on the Mac (on the contrary, it is present in Linux).
A workaround may be a constant initial position of the window.
<img width="405" alt="image" src="https://github.com/user-attachments/assets/33ed0322-97cb-4476-96ef-5bec24abf748">
<img width="405" alt="image" src="https://github.com/user-attachments/assets/189d3689-9872-4303-a129-66a47da86a51">

This QuickDrop works fine in Linux and, with the limitation of the workaround above, in macOS.

Regards,
Maurizio.

**Comment by matrixx567** [comment]
Hi @mbollini,

I've implemented a fix for MAC in version [#v1.3.0.5 ](https://github.com/matrixx567/LabView_QuickDrop_AlignElements/releases/tag/v1.3.0.5).

As described in the README you can set the offsets within the `LabVIEW.ini`.

I don't have a MAC so I can't test this fix. Can you test this release and give me some feedback before I publish this to VIPM.

**Comment by mbollini** [comment]
Hi Martin,

Thanks for your job.

Just change OS with TARGET_TYPE to make the conditional work in a library. OS symbol is recognised in a LV project.
I also tested OK the position parameters in the LabVIEW.ini (which is \Users\<your user>\Library\Preferences\LabVIEW version number on a Mac.

Regards,

Maurizio.

**Comment by matrixx567** [comment]
Hi @mbollini ,

a new release v1.3.0.6 is available on VIPM.

**Comment by mbollini** [comment]
This latest version works perfectly on Mac.
Thanks,
Maurizio.
